#!/system/bin/sh

export PATH=$PATH:/bin:/usr/bin:/system/bin

/system/bin/busybox chroot /debian /usr/bin/killall -s KILL apache2
rm /debian/run/apache2/apache2.pid

sleep 10

source /system/bin/setup_debian

/system/bin/busybox chroot /debian /usr/sbin/apachectl -D NO_DETACH -k start

