#!/system/bin/sh

export PATH=$PATH:/bin:/usr/bin:/system/bin

/system/bin/busybox chroot /debian /usr/bin/killall postgres
rm /debian/run/postgresql/9.4-main.pid

sleep 14

source /system/bin/setup_debian

/system/bin/busybox chroot /debian /bin/su postgres -c "/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgres/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf"

