#!/system/bin/sh

export PATH=$PATH:/bin:/usr/bin:/system/bin
busybox echo -ne \<br /\>SQL Status: \\c 
busybox chroot /debian /etc/init.d/postgresql status
busybox echo -ne \<br /\>Apache2 Status: \\c
busybox chroot /debian /etc/init.d/apache2 status

