#!/system/bin/sh

export PATH=$PATH:/bin:/usr/bin:/system/bin

#source /system/bin/setup_debian

/system/bin/busybox chroot /debian /etc/init.d/postgresql stop
/system/bin/busybox chroot /debian /etc/init.d/apache2 stop
/system/bin/busybox chroot /debian /etc/init.d/cron stop
/system/bin/busybox chroot /debian /etc/init.d/ssh stop
/system/bin/mount -o remount,ro /debian
/system/bin/mount -o remount,ro /data
/system/bin/mount -o remount,ro /cache
/system/bin/mount -o remount,ro /system
echo on > /sys/power/state
echo mem > /sys/power/state

