#!/system/bin/sh

export PATH=$PATH:/bin:/usr/bin:/system/bin

#source /system/bin/setup_debian

sleep 60

/system/bin/stop
/system/bin/busybox chroot /debian /etc/init.d/postgresql stop
/system/bin/busybox chroot /debian /etc/init.d/apache2 stop
/system/bin/busybox chroot /debian /etc/init.d/cron stop
/system/bin/busybox chroot /debian /etc/init.d/ssh stop
/system/bin/mount -o remount,ro /debian/var
/system/bin/mount -o remount,ro /debian
/system/bin/mount -o remount,ro /data
/system/bin/mount -o remount,ro /cache
/system/bin/mount -o remount,ro /system
#echo on > /sys/power/state
#echo mem > /sys/power/state
sync && echo 180 > /sys/devices/soc0/soc.0/2100000.aips-bus/21a0000.i2c/i2c-0/0-0020/powerdown

